# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fault_detection.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 0, 991, 491))
        self.tabWidget.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.exportPushButton = QtWidgets.QPushButton(self.tab)
        self.exportPushButton.setGeometry(QtCore.QRect(790, 350, 121, 41))
        self.exportPushButton.setStyleSheet("border-radius: 10px;  border: 2px groove gray;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/11795/.designer/resource/导出icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportPushButton.setIcon(icon)
        self.exportPushButton.setObjectName("exportPushButton")
        self.deletePushButton = QtWidgets.QPushButton(self.tab)
        self.deletePushButton.setGeometry(QtCore.QRect(590, 350, 81, 41))
        self.deletePushButton.setStyleSheet("border-radius: 10px;  border: 2px groove gray;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/11795/.designer/resource/删除icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deletePushButton.setIcon(icon1)
        self.deletePushButton.setObjectName("deletePushButton")
        self.detailPushButton = QtWidgets.QPushButton(self.tab)
        self.detailPushButton.setGeometry(QtCore.QRect(690, 350, 81, 41))
        self.detailPushButton.setStyleSheet("border-radius: 10px;  border: 2px groove gray;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/11795/.designer/resource/感叹号icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.detailPushButton.setIcon(icon2)
        self.detailPushButton.setObjectName("detailPushButton")
        self.snapshotPushButton = QtWidgets.QPushButton(self.tab)
        self.snapshotPushButton.setGeometry(QtCore.QRect(500, 350, 81, 41))
        self.snapshotPushButton.setStyleSheet("background-color: rgb(207, 0, 0);\n"
"border-color: rgb(85, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;  border: 2px groove gray;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/11795/.designer/resource/相机icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.snapshotPushButton.setIcon(icon3)
        self.snapshotPushButton.setObjectName("snapshotPushButton")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(580, 40, 72, 15))
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(589, 90, 311, 241))
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listWidget.setObjectName("listWidget")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(600, 70, 45, 16))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(630, 70, 24, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(830, 70, 24, 16))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(750, 70, 24, 16))
        self.label_3.setObjectName("label_3")
        self.streamSelectTabWidget = QtWidgets.QTabWidget(self.tab)
        self.streamSelectTabWidget.setGeometry(QtCore.QRect(20, 0, 471, 411))
        self.streamSelectTabWidget.setObjectName("streamSelectTabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.videoPlayer = QVideoWidget(self.tab_5)
        self.videoPlayer.setGeometry(QtCore.QRect(0, 0, 511, 291))
        self.videoPlayer.setStyleSheet("background-color: rgb(94, 94, 94);")
        self.videoPlayer.setObjectName("videoPlayer")
        self.horizontalSlider = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider.setGeometry(QtCore.QRect(110, 310, 291, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.layoutWidget = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 350, 312, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backOffPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.backOffPushButton.setStyleSheet("border-radius: 10px;  border: 2px groove gray;")
        self.backOffPushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/11795/.designer/resource/快退icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backOffPushButton.setIcon(icon4)
        self.backOffPushButton.setObjectName("backOffPushButton")
        self.horizontalLayout.addWidget(self.backOffPushButton)
        self.lastPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.lastPushButton.setStyleSheet("border-radius: 10px;  border: 2px groove gray;")
        self.lastPushButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/Users/11795/.designer/resource/上一个icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lastPushButton.setIcon(icon5)
        self.lastPushButton.setObjectName("lastPushButton")
        self.horizontalLayout.addWidget(self.lastPushButton)
        self.startPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.startPushButton.setStyleSheet("border-radius: 10px;  border: 2px groove gray;")
        self.startPushButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:/Users/11795/.designer/resource/开始.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startPushButton.setIcon(icon6)
        self.startPushButton.setObjectName("startPushButton")
        self.horizontalLayout.addWidget(self.startPushButton)
        self.nextPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.nextPushButton.setStyleSheet("border-radius: 10px;  border: 2px groove gray;")
        self.nextPushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:/Users/11795/.designer/resource/下一个icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextPushButton.setIcon(icon7)
        self.nextPushButton.setObjectName("nextPushButton")
        self.horizontalLayout.addWidget(self.nextPushButton)
        self.fastForwardPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.fastForwardPushButton.setStyleSheet("border-radius: 10px;  border: 2px groove gray;")
        self.fastForwardPushButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:/Users/11795/.designer/resource/跨进icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fastForwardPushButton.setIcon(icon8)
        self.fastForwardPushButton.setObjectName("fastForwardPushButton")
        self.horizontalLayout.addWidget(self.fastForwardPushButton)
        self.oepnVideoPushButton = QtWidgets.QPushButton(self.tab_5)
        self.oepnVideoPushButton.setGeometry(QtCore.QRect(10, 320, 81, 41))
        self.oepnVideoPushButton.setStyleSheet("border-radius: 10px;  border: 2px groove gray;")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:/Users/11795/.designer/resource/文件icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.oepnVideoPushButton.setIcon(icon9)
        self.oepnVideoPushButton.setObjectName("oepnVideoPushButton")
        self.streamSelectTabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.cameraLabel = QtWidgets.QLabel(self.tab_6)
        self.cameraLabel.setGeometry(QtCore.QRect(0, 0, 501, 291))
        self.cameraLabel.setText("")
        self.cameraLabel.setObjectName("cameraLabel")
        self.openCameraPushButton = QtWidgets.QPushButton(self.tab_6)
        self.openCameraPushButton.setGeometry(QtCore.QRect(40, 330, 93, 28))
        self.openCameraPushButton.setObjectName("openCameraPushButton")
        self.cameraSelectPushButton = QtWidgets.QPushButton(self.tab_6)
        self.cameraSelectPushButton.setGeometry(QtCore.QRect(220, 330, 71, 28))
        self.cameraSelectPushButton.setObjectName("cameraSelectPushButton")
        self.cameraStoragePushButton = QtWidgets.QPushButton(self.tab_6)
        self.cameraStoragePushButton.setGeometry(QtCore.QRect(320, 330, 71, 28))
        self.cameraStoragePushButton.setObjectName("cameraStoragePushButton")
        self.streamSelectTabWidget.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.settingPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingPushButton.setGeometry(QtCore.QRect(880, 10, 41, 28))
        self.settingPushButton.setObjectName("settingPushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.streamSelectTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exportPushButton.setText(_translate("MainWindow", "导出当前列表"))
        self.deletePushButton.setText(_translate("MainWindow", "删除"))
        self.detailPushButton.setText(_translate("MainWindow", "详情"))
        self.snapshotPushButton.setText(_translate("MainWindow", " 快照"))
        self.label.setText(_translate("MainWindow", "快照记录"))
        self.label_2.setText(_translate("MainWindow", "时间"))
        self.label_4.setText(_translate("MainWindow", "编号"))
        self.label_3.setText(_translate("MainWindow", "类型"))
        self.oepnVideoPushButton.setText(_translate("MainWindow", "打开..."))
        self.streamSelectTabWidget.setTabText(self.streamSelectTabWidget.indexOf(self.tab_5), _translate("MainWindow", "视频"))
        self.openCameraPushButton.setText(_translate("MainWindow", "打开摄像头"))
        self.cameraSelectPushButton.setText(_translate("MainWindow", "设备选择"))
        self.cameraStoragePushButton.setText(_translate("MainWindow", "历史副本"))
        self.streamSelectTabWidget.setTabText(self.streamSelectTabWidget.indexOf(self.tab_6), _translate("MainWindow", "直播"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "缺陷检测"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "识别训练"))
        self.settingPushButton.setText(_translate("MainWindow", "设置"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
